events {
    worker_connections 1024;
}

http {
    upstream partidas {
        server partidas-service:8081;
    }

    upstream carteira {
        server carteira-service:8080;
    }

    server {
        listen 80;

        location /partidas/ {
            proxy_pass http://partidas/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /wallet/ {
            proxy_pass http://carteira/wallet/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
