quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=${QUARKUS_DATASOURCE_REACTIVE_URL:postgresql://localhost:5434/carteira_db}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:bolao}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:bolao}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.redis.hosts=${QUARKUS_REDIS_HOSTS:redis://localhost:6379}

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
mp.messaging.incoming.bet-events.connector=smallrye-kafka
mp.messaging.incoming.bet-events.topic=bet-events
mp.messaging.incoming.bet-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.bet-events.group.id=carteira-service-bet-group
mp.messaging.incoming.bet-events.failure-strategy=dead-letter-queue
mp.messaging.incoming.bet-events.dead-letter-queue.topic=bet-events-dlq
mp.messaging.incoming.user-events.connector=smallrye-kafka
mp.messaging.incoming.user-events.topic=user-events
mp.messaging.incoming.user-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.user-events.group.id=carteira-service-user-group
mp.messaging.incoming.user-events.failure-strategy=dead-letter-queue
mp.messaging.incoming.user-events.dead-letter-queue.topic=user-events-dlq
quarkus.http.port=8080

mp.messaging.outgoing.wallet-events.connector=smallrye-kafka
mp.messaging.outgoing.wallet-events.topic=wallet-events
mp.messaging.outgoing.wallet-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
